from pydantic import BaseModel
from loguru import logger


# Data model for search requests
class SearchRequest(BaseModel):
    query: str
    session_id: str = None

    def __init__(self, **data):
        super().__init__(**data)
        logger.info(
            f"Initialized SearchRequest with query='{self.query}', session_id='{self.session_id}'"
        )


# ----------- LangGraph Setup -----------


# Data model for conversation state in LangGraph
class ConversationState(BaseModel):
    conversation: list  # List of conversation messages or turns
    query: str = ""  # Current user query
    transformed_query: str = ""  # Query optimized by an LLM for retrieval
    retrieved_documents: list = []  # Documents retrieved from the vector store
    follow_up_question: str = ""  # Follow-up question generated by the system
    recommendation: str = ""  # Recommendation generated by the system
    recommendation_query: str = ""  # Query used for generating recommendation
    is_follow_up: str = ""  # Flag indicating if the current state is a follow-up
    citations: list = []  # List of citations or references
    ready_for_recommendation: bool = (
        False  # Flag indicating readiness for recommendation
    )
    follow_up_count: int = 0  # Track number of follow-ups


    def __init__(self, **data):
        super().__init__(**data)
        logger.info(
            f"Initialized ConversationState with conversation={self.conversation}, "
            f"query='{self.query}', follow_up_question='{self.follow_up_question}', "
            f"recommendation='{self.recommendation}', recommendation_query='{self.recommendation_query}', "
            f"citations={self.citations}, ready_for_recommendation={self.ready_for_recommendation}"
        )
